version: '3.8'
services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 90:80
      - 553:443
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
      - server
    networks:
      - app-network
    volumes:
      - ./:/var/www
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
